swiftmailer:
#    url: '%env(MAILER_URL)%'

#   Ez működik a Szerverről is !!
    transport: smtp
    host:      mail.rafina.hu
    username:  info@rafina.hu
    password:  Kopogtato2021
    encryption: ssl
    auth_mode: login
    port: 465

#    Ez csak localisan működik
#
#    transport:  smtp
#    host:       smtp.gmail.com
#    username:   rafinadekor@gmail.com
#    password:   Kopogtato2021
#    encryption: ssl
#    auth_mode:  login
#    port:       465

    spool: { type: 'memory' }
