framework:
    default_locale: '%locale%'
    translator:
#        default_path: '%kernel.project_dir%/translations'
#        fallbacks:
#            - en

        paths:
            - '%kernel.project_dir%/translations'
            - '%kernel.project_dir%/translations/admin'
            - '%kernel.project_dir%/translations/store'
        fallbacks:
#            - '%locale%'
            - 'hu'
            - 'en'